# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _site
host:             0.0.0.0
port:             9001
baseurl:          ""
url:              https://eresearch.jcu.io
encoding:         UTF-8
timezone:         Australia/Brisbane
exclude:          [assets/scss/]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom vars
current_version:  0.1
repo:             https://github.com/jcu/eresearch-blog-web-framework



blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com
